---
title: "Statistical Analysis Of Inversion Marker Frequencies "
author: "S.Steindl"
date: '2023-03-29'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#                                 TYPE 3 ANOVA 

```{r libraries, include=FALSE}
library(car)
library(readr)
library(knitr)
```

```{r prepare_data, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
meta <- read.csv("/media/DEST2_NHM/data/dest_v2.samps_25Feb2023.csv", row.names=1)

#POOL-SNP
nhm_inversion <- read.delim("/media/DEST2_NHM/results/PoolSNP_nhm_inversion.af", row.names=1)
for (col in colnames(nhm_inversion)){
  nhm_inversion[[col]] <- as.numeric(paste(nhm_inversion[[col]]))
}  

joined_table <- merge(meta[3:5], nhm_inversion, by = "row.names")
rownames(joined_table) <- rownames(meta)
data <- merge(meta[13:14], joined_table, by ="row.names")

##Get Coverages for correspronding data set
mean_coverages <- read.csv("/media/DEST2_NHM/output/CoveragesPoolSNP.csv", header=FALSE)
cov <- t(round(mean_coverages))
data$cov <- cov[,1] 
data <- na.omit(data) 

#Inversions
inversions=c("In.3R.Payne", "In.2L.t", "In.2R.Ns", "In.3R.C", "In.3R.K", "In.3R.Mo", "In.3L.P")

for (i in 8:14){
  #print(data[i])
  x <- paste("ANOV_",colnames(data[i]),"_1", sep="")
  x2 <- paste("ANOV_",colnames(data[i]),"_2", sep="")
  v <- round(data[i]*data$cov)
  v2 <- round(data$cov - round(data[i]*data$cov,0),0)
  p <- assign(x,v)
  p2 <- assign(x2,v2)
  colnames(p) <- x
  colnames(p2) <- x2
  data <- cbind(data,p)
  data <- cbind(data,p2)
}

my_splits <- split(data, data$continent)
split_names <- c("Africa",           
                 "Asia",
                 "Europe",
                 "North_America","Oceania", "South_America")
for (i in 1:length(my_splits)) {       
  assign(split_names[i], my_splits[[i]])
}
ContList <- list(Africa, Asia, Europe, North_America, Oceania, South_America)

#ANOVA Type3 


#function for 3 paramters inclduing continent, usable globally 
latloncont <- function(subs){
  data=subs
  for (inv in inversions){
    t <- paste(inv,"_test", sep="")
    c1 <- paste("ANOV_",inv,"_1", sep="")
    c2 <- paste("ANOV_",inv,"_2", sep="")
    #print(data[[c1]] )
    x <- glm(cbind(data[[c1]] ,data[[c2]])~lat*long*continent,data=data,family="binomial" )
    r <- car::Anova(x, type=3)
    print(kable(r, format="pandoc", caption = paste(inv)))
    #cat("\n")
    #assign(t,x)
  } 
}



###

latlon <- function(subs){
  data <- subs
  for (inv in inversions){
    t <- paste(inv,"_test", sep="")
    c1 <- paste("ANOV_",inv,"_1", sep="")
    c2 <- paste("ANOV_",inv,"_2", sep="")
    #print(data[[c1]] )
    x <- glm(cbind(data[[c1]] ,data[[c2]])~lat*long,data=data,family="binomial" )
    r <- car::Anova(x, type=3)
    #kable(r, format="pandoc", caption = paste(inv))
    print(kable(r, format="pandoc", caption = paste(inv)))
    #cat("\n")
    #assign(t,x)
  } 
}  

#lapply(ContList, latlon(x))

```
# All Inversions - Global

```{r plot, echo= FALSE,comment="", prompt=TRUE, fig.align="center"} 

latloncont(data)

```

# All Inversions Per Continent

## 1) Europe
```{r plotEurope, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Europe)

```

## 2) North America
```{r plotNA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(North_America)
```

## 3) South America
```{r plotSA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(South_America)
```
## 4) Oceania
```{r plotOA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Oceania)
```
## 5) Africa
```{r plotA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Africa)
```